# RAG Chatbot Frontend Demo Launcher
# Runs the frontend in demo mode without requiring API Gateway
# Copyright (c) 2025 RAG Chatbot Project

Write-Host ""
Write-Host "🤖 RAG Chatbot Frontend - Demo Mode" -ForegroundColor Green
Write-Host "====================================" -ForegroundColor Green
Write-Host "   Running frontend without backend for preview" -ForegroundColor Gray
Write-Host ""

# Check if we're in the right directory
if (-not (Test-Path "application/frontend/app.py")) {
    Write-Host "❌ Error: Please run this script from the project root directory" -ForegroundColor Red
    Write-Host "   Current directory: $(Get-Location)" -ForegroundColor Yellow
    exit 1
}

# Check Python
try {
    $pythonVersion = python --version 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "Python not found"
    }
    Write-Host "✅ Python found: $pythonVersion" -ForegroundColor Green
} catch {
    Write-Host "❌ Python not found. Please install Python 3.11 or later." -ForegroundColor Red
    exit 1
}

# Install Streamlit if not present
Write-Host "📦 Checking Streamlit..." -ForegroundColor Yellow
try {
    $streamlitVersion = streamlit --version 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "Streamlit not found"
    }
    Write-Host "✅ Streamlit found: $streamlitVersion" -ForegroundColor Green
} catch {
    Write-Host "⚠️  Installing Streamlit..." -ForegroundColor Yellow
    pip install streamlit requests python-dotenv
    if ($LASTEXITCODE -eq 0) {
        Write-Host "✅ Streamlit installed successfully" -ForegroundColor Green
    } else {
        Write-Host "❌ Failed to install Streamlit" -ForegroundColor Red
        exit 1
    }
}

# Create demo environment file
Write-Host "🔧 Setting up demo environment..." -ForegroundColor Yellow
$envContent = @"
# RAG Chatbot Demo Environment Configuration
# Generated by demo-frontend.ps1 on $(Get-Date)

API_GATEWAY_URL=https://demo-api.execute-api.region.amazonaws.com/prod
ENVIRONMENT=demo
"@

$envFile = "application/frontend/.env"
$envContent | Out-File -FilePath $envFile -Encoding UTF8 -Force
Write-Host "✅ Demo environment file created" -ForegroundColor Green

# Set environment variables for demo
$env:API_GATEWAY_URL = "https://demo-api.execute-api.region.amazonaws.com/prod"
$env:ENVIRONMENT = "demo"

Write-Host ""
Write-Host "🚀 Starting RAG Chatbot Frontend in Demo Mode..." -ForegroundColor Green
Write-Host "=================================================" -ForegroundColor Green
Write-Host ""
Write-Host "📱 The application will open in your default browser" -ForegroundColor Cyan
Write-Host "⚠️  Note: This is demo mode - API calls will fail but you can see the UI" -ForegroundColor Yellow
Write-Host "🛑 Press Ctrl+C to stop the server" -ForegroundColor Gray
Write-Host ""

# Change to frontend directory and run
Push-Location "application/frontend"
try {
    streamlit run app.py --server.port 8501 --server.address localhost --browser.gatherUsageStats false
} finally {
    Pop-Location
}

Write-Host ""
Write-Host "👋 Demo session ended." -ForegroundColor Cyan
Write-Host "To deploy the full system, run 'terraform apply' in infrastructure/terraform/" -ForegroundColor Yellow
